# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MakeCustomOTPView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OTPFieldView'
  

  # Pods for MakeCustomOTPView

  target 'MakeCustomOTPViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MakeCustomOTPViewUITests' do
    # Pods for testing
  end

end
